name: Pull Request CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests on Pull Request
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write # Permitir escribir comentarios en los PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Comment start of pipeline
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "CI/CD en acción. Ejecutando tareas …"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/

      - name: Comment success of pipeline
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "CI/CD terminado con éxito."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve Pull Request
        if: success() && github.event_name == 'pull_request'
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
