name: Pull Request CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests on Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Comment start of pipeline
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "CI/CD en acción. Ejecutando tareas …"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/

      - name: Comment success of pipeline
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "CI/CD terminado con éxito."
